//API相关
//发布状态的主机地址
PRODUCT_HOST="http://h6.duchengjiu.top/shop/";
//测试状态下的主机地址
DEBUG_HOST="192.168.200.33:8080/shop/";
//登录
LOGIN="api_user.php";
//获取商品分类
PRODUCT_TYPE="api_cat.php";
//通过商品分类获得商品列表
GOODS="api_goods.php";
